// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFJK_kkDTIYRiRk48kz13zn_5jB-LVGB8',
    appId: '1:629507801106:web:8998e627b10cd384cd58cb',
    messagingSenderId: '629507801106',
    projectId: 'glossario-de-oclusao',
    authDomain: 'glossario-de-oclusao.firebaseapp.com',
    storageBucket: 'glossario-de-oclusao.appspot.com',
    measurementId: 'G-LXXW92NM00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFav411BJahfM4fG9T-eCQ52jEC4dLXIs',
    appId: '1:629507801106:android:5db4ac1488598766cd58cb',
    messagingSenderId: '629507801106',
    projectId: 'glossario-de-oclusao',
    storageBucket: 'glossario-de-oclusao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM7cMAT2S04nNtzK3PqwfsGey6AhwLX4Y',
    appId: '1:629507801106:ios:444fa6c77dde2f2dcd58cb',
    messagingSenderId: '629507801106',
    projectId: 'glossario-de-oclusao',
    storageBucket: 'glossario-de-oclusao.appspot.com',
    iosClientId: '629507801106-u20ji4gbko7bkcdi7cquoe5gdsrvhtd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.glossarioDeOclusao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM7cMAT2S04nNtzK3PqwfsGey6AhwLX4Y',
    appId: '1:629507801106:ios:444fa6c77dde2f2dcd58cb',
    messagingSenderId: '629507801106',
    projectId: 'glossario-de-oclusao',
    storageBucket: 'glossario-de-oclusao.appspot.com',
    iosClientId: '629507801106-u20ji4gbko7bkcdi7cquoe5gdsrvhtd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.glossarioDeOclusao',
  );
}
